name: cicd in github actions

on: 
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v4

      - name: initialize repo

        run: |
          echo "This is IKram Slaam"
          uname -a

      - name: check the docker installation

        run: |
          docker
          docker images

      - name: run docker container

        run: |
          docker run hello-world
