name: cicd in github actions

on: 
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@v4

      - name: my first step

        run: |
          echo "This is IKram Slaam"
          uname -a
